Documentation and Issue #1204
CDH-Studio/UpSkill pull request #1206
Opened 2021-01-06 15:21 UTC by ianwilk20

#### Changes introduced
Added documentation to README to describe how to setup Image Devices with Docker and get I-Talent running.

#### Related issue(s)
fixes #1204

2021-01-06 15:49 UTC, dynamic11 requested changes

2021-01-06 15:49 UTC, dynamic11 commented on README.md
> +Press on "Close and restart" (Note: This will restart Windows)
you can just say "Download and install Docker Desktop" instead of going into detail about the installation process

2021-01-06 15:49 UTC, dynamic11 commented on README.md
> +Run the installer
you can just say "Download and install Visual Studio Code" instead of going into detail about the installation process

2021-01-06 15:49 UTC, dynamic11 commented on README.md
> +Ensure that a Git version is displayed following the command, if not, follow this guide to add Git to the path https://asbscr.ic.gc.ca/scm/projects/CIODD/repos/cio-developer-handbook/browse/chapters/
this is only available "on prem" so i wouldn't put it here

2021-01-06 15:55 UTC, dynamic11 commented
All the text is bunched up. please make it into a list style.
![image](https://user-images.githubusercontent.com/11470442/103788836-4d808f80-500d-11eb-82a8-461da700df10.png)

you can use these elements to style the markdown:
[markdown guide](https://www.markdownguide.org/basic-syntax/)

2021-01-13 21:17 UTC, MohamedRadwan approved these changes
Looks good

2021-03-30 22:40 UTC, MohamedRadwan commented
Is this good to be merged ?

2021-05-04 15:21 UTC, dynamic11 commented
No it is not. It should be converted to draft for now

2021-05-21 15:25 UTC, closed without merging