[New] Created Admin Schools Table/Page
CDH-Studio/UpSkill pull request #131
Opened 2020-04-24 05:27 UTC by SukhsimranpreetSekhon

- Added Schools Table/Page to Admin side
- Able to add, edit and delete school information (name, location & country)
- Can search through the information in the table
- English/French translation
- Added access from the sidebar to table/page

2020-04-24 05:47 UTC, dynamic11 requested changes

2020-04-24 05:47 UTC, dynamic11 commented on yarn.lock
> +
Don't commit this file change

2020-04-24 19:39 UTC, SukhsimranpreetSekhon commented on yarn.lock
> +
Fixed.

2020-04-25 19:36 UTC, dynamic11 approved these changes

2020-04-25 19:43 UTC, merged