Visibility Confirm Modal
CDH-Studio/UpSkill pull request #1335
Opened 2021-04-29 20:25 UTC by Rizvida1

#### Changes introduced

Upon finishing a form, a modal will pop up showing the current visibility.

#### Related issue(s)

Closes #1125 

#### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/31704878/116613156-58d23080-a906-11eb-9437-06a284b3013f.png)

If the UI has been modified:
- [X] It is translated in both language (with no hard coded text) 
- [X] Has been tested on IE
- [X] The modifications are tab friendly
- [X] It is accessible

2021-04-30 15:49 UTC, MenaMachado commented
@Rizvida1 , why does Employment Status say "connection"?

2021-04-30 16:01 UTC, Rizvida1 commented
@MenaMachado "Connections" is one of the options of visibility. It can either be private, public or connections only.

2021-04-30 16:10 UTC, MenaMachado commented
@Rizvida1 , thanks for the reminder, I'm wondering if we should rename "connections" to "private group" for clarity but we can discuss that as a team and with the client. Also, must OL have 3 items?

2021-04-30 16:16 UTC, Rizvida1 commented
@MenaMachado Thanks for pointing out the OL. It has been fixed.

2021-04-30 16:30 UTC, MenaMachado commented
@Rizvida1 - better!

2021-05-06 20:44 UTC, MohamedRadwan requested changes

2021-05-06 20:44 UTC, MohamedRadwan commented on services/frontend/src/components/profileForms/formControlButtons/FormControlButtonsView.jsx
> +  console.log("ONFINISH", typeof onFinish);
Do you need the console log here?

2021-05-06 20:44 UTC, MohamedRadwan commented on services/frontend/src/components/visibilityConfirmation/VisibilityConfirmationView.jsx
> +      case "PUBLIC":
can this be changed to a function with variables being passed in for each case since its repeated code

2021-05-07 13:24 UTC, MohamedRadwan approved these changes

2021-05-07 14:21 UTC, merged

2021-05-11 21:09 UTC, dynamic11 commented
I just noticed that this error has been introduced due to this PR (I think):
![image](https://user-images.githubusercontent.com/11470442/117885252-a0987680-b27b-11eb-9a95-9d6189587a08.png)

2021-05-11 21:16 UTC, Rizvida1 commented
> @Rizvida1 I just noticed that this error has been introduced due to this PR (I think):
> ![image](https://user-images.githubusercontent.com/11470442/117885252-a0987680-b27b-11eb-9a95-9d6189587a08.png)

This is fixed in PR #1368