[Fix] Remove acting date
CDH-Studio/UpSkill pull request #1347
Opened 2021-05-04 17:57 UTC by MohamedRadwan

#### Changes introduced

#### Related issue(s)

#### Screenshots (if applicable)

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

2021-05-06 19:13 UTC, Rizvida1 requested changes
Would it make sense to remove the corresponding translations in the i18n files?

2021-05-06 20:17 UTC, MohamedRadwan commented
> Would it make sense to remove the corresponding translations in the i18n files?

Good catch. Done

2021-05-07 14:45 UTC, mo-5 commented
Could you please recheck this ?

2021-05-07 15:36 UTC, Rizvida1 approved these changes

2021-05-07 15:38 UTC, merged