[New] Updates to i18 validation and update the i18n files along with the blacklist files
CDH-Studio/UpSkill pull request #1451
Opened 2021-06-10 05:17 UTC by mo-5

#### ⭐ Changes introduced

- Added new validation to see what i18 keys are used in the application but not in translation to prevent having "visibility.selector" something like this in production 
- Updated the i18n file with the excel file
- Cleaned up the missing keys in the admin page 
- Fixed a few edge cases in the validation 
- Before merging please confirm the translation of the following: "visibility.selector": "Select visibility",  "visibility.selector": "Sélectionnez la visibilité",
- Update to my circle

#### 🔗 Related issue(s)

closes #1449, closes #1431, closes #1390, closes #1377

#### 📸 Screenshots (if applicable)

#### ☑️ Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hard coded text) 
- [ ] The modifications are tab friendly
- [ ] It is accessible

If translations have been modified:
- [ ] run `yarn i18n:validate" and clear errors

2021-06-10 15:47 UTC, dynamic11 requested changes
please see comments. Also please remove mena's translations into a separate PR

2021-06-10 15:47 UTC, dynamic11 commented on services/frontend/src/i18n/tools/validation.js
> +  // Remove all blacklisted key from the check
repeat

2021-06-10 15:47 UTC, dynamic11 commented on services/frontend/src/i18n/tools/validationHelperFunctions.js
> -  // function to search for key in file content
please move this comment to change

2021-06-10 15:47 UTC, dynamic11 commented on services/frontend/src/i18n/tools/validationHelperFunctions.js
> +const findMissingTranslations = async (
please add comment to function

2021-06-10 15:47 UTC, dynamic11 commented on services/frontend/src/i18n/tools/validationHelperFunctions.js
> +          if (
maybe we should move this into a separate function. let me know what you think :)

2021-06-15 15:18 UTC, Rizvida1 approved these changes

2021-06-15 16:21 UTC, dynamic11 commented on services/frontend/src/i18n/tools/validationHelperFunctions.js
> + * @returns {string[]}
better comments needed

2021-06-15 16:25 UTC, dynamic11 approved these changes
approved but please see minor comment

2021-06-15 16:55 UTC, merged