[Fix] The ability to bypass step 2 via the url
CDH-Studio/UpSkill pull request #1604
Opened 2021-08-06 03:28 UTC by mo-5

#### ⭐ Changes introduced

This will prevent the user from bypassing step 2 via URL once they reach step 3 they will be able to go to any step. I changed quite a few things with the routing so please test it out and let me know if you notice anything breaking.

#### 🔗 Related issue(s)

closes #1543

#### 📸 Screenshots (if applicable)

#### ☑️ Checklist

If the database has been modified:

- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints has been modified:

- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak

If the UI has been modified:

- [ ] It is translated in both language (with no hard coded text) 
- [ ] The modifications are tab friendly
- [ ] It is accessible

If translations have been modified:

- [ ] run `yarn i18n:validate" and clear errors

2021-08-06 13:20 UTC, dynamic11 commented on services/frontend/src/components/profileForms/primaryInfoForm/PrimaryInfoFormView.jsx
> +import { setUserSignupStep } from "../../../redux/slices/userSlice";
import these above the *.less file

2021-08-06 13:20 UTC, dynamic11 requested changes
I tested the change and it seems to be working well. Just one formatting comment

2021-08-06 14:14 UTC, mo-5 commented on services/frontend/src/components/profileForms/primaryInfoForm/PrimaryInfoFormView.jsx
> +import { setUserSignupStep } from "../../../redux/slices/userSlice";
done

2021-08-10 18:13 UTC, dynamic11 approved these changes

2021-08-10 18:16 UTC, merged