[Fix] Refactor all profile cards for improved a11y and clean up
CDH-Studio/UpSkill pull request #1689
Opened 2021-10-18 14:39 UTC by dynamic11

#### ⭐  Changes introduced
- Reorganized heading structure for profile page (a11y)
- Refactor "Skills Card" and "Mentorship Card" to use correct headings for skill categories (a11y)
- Refactor "Dev Goals Card" to add heading for supporting documents (a11y)
- Fixed bug in "Dev Goals Card" that shoed empty card message even though supporting docs were present (bug)
- Refactor "Education Card" Items to a have a more accessible layout (a11y)
- Refactor "Experience Card" Items to a have a more accessible layout (a11y)
- Refactor "Qualified Pools Card" to a have a more accessible layout (a11y)
- Refactor "Talent Management Card" to a have a more accessible layout (a11y)
- Refactor "Job Mobility Card" to a have a more accessible layout (a11y)
- Added "empty message" for "About Me Card" (a11y)
- Redirect links on the profile page now all tell the screen reader they will redirect (a11y)
- Improved JS Docs for profile cards (documentation)
- Updated Profile Card filenames to be more descriptive (documentation)

#### 🔗 Related issue(s)
closes #1376
closes #1563
closes #1689 
closes #1564 
closes #1676 

#### 📸 Screenshots (if applicable)
The entire profile page as been slightly polish and modified

#### ☑️ Checklist

If the UI has been modified:
- [x] It is translated in both language (with no hard coded text) 
- [x] The modifications are tab friendly
- [x] It is accessible

If translations have been modified:
- [x] run `yarn i18n:validate" and clear errors

2021-10-18 19:22 UTC, P4ul1029 commented on services/frontend/src/components/officialLanguageCard/OfficialLanguageCard.jsx
>     * @return {Array.<{description: String, title: String}>} - array of first language results
Should change the description and `@return` line to reflect that the function now returns an object instead of an array of first language results.

2021-10-18 19:45 UTC, P4ul1029 commented on services/frontend/src/components/educationCard/EducationCardView.jsx
> +   * @param {string} SupportingLinks.id - Unique id the document
Did you mean `Unique id of the document` in this comment?

2021-10-18 19:46 UTC, P4ul1029 commented on services/frontend/src/components/experienceCard/ExperienceCardView.jsx
> +   * @param {string} SupportingLinks.id - Unique id the document
Did you mean `Unique id of the document` in this comment?

2021-10-18 19:46 UTC, P4ul1029 commented on services/frontend/src/components/learningDevelopment/LearningDevelopmentView.jsx
> +   * @param {string} SupportingLinks.name.id - Unique id the document type
Did you mean `Unique id of the document` in line 41 and 45?

2021-10-18 19:58 UTC, P4ul1029 commented
I switched onto this branch and editted all the aspects of my profile and ran into no issues.

When I tried to view a mock user's profile though, I ran into issue #1682:
![image](https://user-images.githubusercontent.com/46769064/137798181-7f84a0bb-b966-48cf-a279-c250d5688130.png)
Should this be fixed in this PR or a future one?

2021-10-18 20:04 UTC, P4ul1029 requested changes
See comments above.

2021-10-19 13:27 UTC, dynamic11 commented
> I switched onto this branch and editted all the aspects of my profile and ran into no issues.
> 
> When I tried to view a mock user's profile though, I ran into issue #1682: ![image](https://user-images.githubusercontent.com/46769064/137798181-7f84a0bb-b966-48cf-a279-c250d5688130.png) Should this be fixed in this PR or a future one?

I cant reproduce this bug...

2021-10-19 17:24 UTC, Rizvida1 approved these changes
Works well for me

2021-10-19 17:24 UTC, P4ul1029 approved these changes
LGTM!

2021-10-19 17:55 UTC, merged