Added placeholders for phone number inputs
CDH-Studio/UpSkill pull request #1747
Opened 2021-12-03 21:06 UTC by P4ul1029

#### ⭐ Changes introduced

Added placeholders for the phone number inputs on the _Edit profile_ page.

#### 🔗 Related issue(s)

closes #1745 

#### 📸 Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/46769064/144672653-e1f0000a-522a-41e2-99a8-0479e5126ce5.png)

#### ☑️ Checklist

2021-12-07 01:30 UTC, dynamic11 commented
Please make sure screen reader reads the format. If it doesn't then try adding the format to the field label

2021-12-07 01:31 UTC, dynamic11 requested changes
Please make sure screen reader also reads the format. If it doesn't then try adding the format to the field label

2021-12-07 16:33 UTC, P4ul1029 commented
> Please make sure screen reader also reads the format. If it doesn't then try adding the format to the field label

The screen reader reads the format stating: "hint, 3 pound signs, 3 pound signs, 4 pound signs".

2021-12-10 15:08 UTC, dynamic11 approved these changes

2021-12-10 16:08 UTC, merged