[Fix] make experience description non required
CDH-Studio/UpSkill pull request #391
Opened 2020-06-15 11:55 UTC by TrevorBivi

Makes the description for experience items be non required

2020-06-16 18:03 UTC, dynamic11 requested changes
Just a side note that i observed:
The description doesn't store "enter" so user cant format their text

2020-06-22 16:09 UTC, TrevorBivi commented
> Just a side note that i observed:
> The description doesn't store "enter" so user cant format their text

2020-06-22 16:28 UTC, TrevorBivi commented on services/frontend-v3/src/components/profileForms/qualificationsForm/experienceForm/ExperienceFormView.jsx
> -          rules={[Rules.required, Rules.maxChar250]}
Just making a public comment that this is being added in another PR after backend changes are merged as discussed in last meeting

2020-06-23 15:05 UTC, dynamic11 approved these changes

2020-06-24 13:32 UTC, merged