[New] Project subsection
CDH-Studio/UpSkill pull request #812
Opened 2020-08-21 20:04 UTC by MohamedRadwan

#### Changes introduced
Added project as a subsection of experience.

#### Related issue(s)
closes #673

#### Screenshots (if aplicable)
![image](https://user-images.githubusercontent.com/21133129/90930432-9c17ef00-e3c8-11ea-8171-9fdf4166c867.png)

![image](https://user-images.githubusercontent.com/21133129/90930251-42afc000-e3c8-11ea-8fa1-21d9f2b37aae.png)

#### Checklist
If the database has been modified:
- [x] Update database diagram 
- [x] Create new migration 

If API endpoints has been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [x] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [x] It is translated in both language (with no hard coded text) 
- [ ] Has been tested on IE
- [x] The modifications are tab friendly
- [x] It is accessible

2020-08-21 20:19 UTC, BenJeau reviewed
Looks good, one small comment - Just need to test it locally

2020-08-29 05:51 UTC, dynamic11 requested changes

2020-08-29 05:51 UTC, dynamic11 commented on services/backend/package.json
> +    "axios": "^0.20.0",
Maybe we should do this upgrade in a separate PR in case it starts causing issues (it will be easier to isolate)

2020-09-02 13:12 UTC, BenJeau commented
Aside from @dynamic11 comment (prisma 2.6 just got release!), the code seems to work fine :100:, the only change I would do is making the tags gray instead of green (for projects and links)

2020-09-02 15:30 UTC, MohamedRadwan commented
Should now be resolved

2020-09-02 15:31 UTC, BenJeau commented
I'll try it right now

2020-09-02 15:40 UTC, BenJeau commented
Two small comments

1. I think the color of the tag is a bit light, I think it should be the same as the others, #727272
![image](https://user-images.githubusercontent.com/22248828/92005011-efffcd80-ed10-11ea-819b-0e50e5e18b44.png)

2. The tags in the forms is not the same styles as the others in forms (I think you just need to add a className to the input)
![image](https://user-images.githubusercontent.com/22248828/92005076-027a0700-ed11-11ea-89af-ad9504a94b4d.png)
![image](https://user-images.githubusercontent.com/22248828/92005101-0a39ab80-ed11-11ea-9032-02f0c918c269.png)

2020-09-02 15:57 UTC, MohamedRadwan commented
Shape and colour have been changed:
1.
![image](https://user-images.githubusercontent.com/21133129/92006952-55ed5480-ed13-11ea-8635-642f2bb4f9d4.png)
2.
![image](https://user-images.githubusercontent.com/21133129/92006977-5b4a9f00-ed13-11ea-91e8-b533e380ac3d.png)

2020-09-02 15:57 UTC, BenJeau approved these changes

2020-09-02 15:59 UTC, dynamic11 approved these changes

2020-09-02 15:59 UTC, merged