[Fix] Search bar on home page does not have label.
CDH-Studio/UpSkill pull request #946
Opened 2020-10-08 20:12 UTC by SukhsimranpreetSekhon

#### Changes introduced

- The search bar form input now has a label for English and French translation that will help for accessibility and screen reading.

#### Related issue(s)

fixes #945

#### Screenshots (if applicable)

English:
![image](https://user-images.githubusercontent.com/35780281/95508230-a85c0980-0980-11eb-8ae2-0d925bf805f3.png)

French:
![image](https://user-images.githubusercontent.com/35780281/95508336-cfb2d680-0980-11eb-81f4-2938c443c02e.png)

#### Checklist
If the database has been modified:
- [ ] Update database diagram 
- [ ] Create new migration 

If API endpoints have been modified:
- [ ] Update backend documentation 
- [ ] Create/Update validators for the API endpoints 
- [ ] The API endpoints are properly secured with keycloak 

If the UI has been modified:
- [ ] It is translated in both language (with no hardcoded text) 
- [ ] Has been tested on IE
- [ ] The modifications are tab friendly
- [ ] It is accessible

2020-10-09 04:37 UTC, dynamic11 commented
can you try rounding the search field using something similar to this:
https://stackoverflow.com/questions/42765528/how-to-make-rounded-raisedbutton-and-textfield

I'm not sure how it will look but lets talk about tomorrow quickly

2020-10-09 19:24 UTC, MenaMachado commented
I agree with Ali's suggestion

2020-10-21 18:38 UTC, dynamic11 commented on services/frontend-v3/src/components/searchBar/SearchBarView.jsx
> +        style={{ width: "100%" }}
can you move this to the css file

2020-10-21 18:38 UTC, dynamic11 commented on services/frontend-v3/src/components/searchBar/SearchBarView.jsx
> +          <text style={{ color: "white" }}>
same here

2020-10-21 18:38 UTC, dynamic11 requested changes
pls see comments

2020-10-27 19:11 UTC, SukhsimranpreetSekhon commented on services/frontend-v3/src/components/searchBar/SearchBarView.jsx
> +        style={{ width: "100%" }}
Fixed.

2020-10-27 19:11 UTC, SukhsimranpreetSekhon commented on services/frontend-v3/src/components/searchBar/SearchBarView.jsx
> +          <text style={{ color: "white" }}>
Fixed.

2020-10-27 19:13 UTC, SukhsimranpreetSekhon commented
> pls see comments

Fixed issues.

2020-10-28 05:45 UTC, dynamic11 approved these changes

2020-10-28 15:31 UTC, merged